spring.application.name=commerce-search-lab

search.elasticsearch.enabled=${ES_ENABLED:false}
search.elasticsearch.url=${ES_URL:}
search.elasticsearch.username=${ES_USERNAME:}
search.elasticsearch.password-file=${ES_PASSWORD_FILE:}
search.elasticsearch.ca-certificate=${ES_CA_CERT:}
search.elasticsearch.connect-timeout=${ES_CONNECT_TIMEOUT:5s}
search.elasticsearch.request-timeout=${ES_REQUEST_TIMEOUT:40s}
